title: Jose Juico | Digital Portfolio
name: Jose Juico
nickname: Brad
description: Digital Portfolio and Developer Playground
email: josejuico@gmail.com
copyright: "&copy; 2026 Jose Juico"
linkedin_username: josejuico
github_username: josejuico

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag